version: '3.8'

services:
  portfolio-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  portfolio-prod:
    build:
      context: .
      target: final
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production