version: '3.8'

services:
  portfolio-dev:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=test
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - test-network
    command: npm run dev

  portfolio-test:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=test
    ports:
      - "3001:80"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge